name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  logger: ^2.0.2+1
 
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  open_file: ^3.3.2
  flutter_windowmanager: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter_pdfview: ^1.3.2
  path: ^1.8.3
  webview_flutter: ^2.0.14
  webview_windows: ^0.4.0
  advance_pdf_viewer: ^2.0.0-nullsafety.3
  syncfusion_flutter_pdfviewer: ^24.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 